language: python
python:
  - "3.11"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - flake8
  - black --check .
  - python manage.py makemigrations --check --dry-run
  - pytest --cov=polls --cov=mysite --cov-report=term-missing --cov-report=html

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: assignment1
  env: assignment1-env
  bucket_name: elasticbeanstalk-us-west-2-626064810330
  on:
    branch: main
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY

cache:
  pip: true

