branch-defaults:
  default:
    environment: assignment1-env
    group_suffix: null
global:
  application_name: Assignment1
  branch: null
  default_ec2_keyname: SE-assignment1
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
